version: '3'
services:
  web:
    build: .
    image: nginx-proxy-owncloud
    container_name: nginx-proxy-owncloud
    ports:
      - "443:443"
      - "80:80"
    external_links:
      - owncloud_1
networks:
  default:
    external:
      name: owncloud_frontend
