version: '2.1'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - OWNCLOUD_SESSION_SAVE_HANDLER=redis
      - OWNCLOUD_SESSION_SAVE_PATH=tcp://redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.entrypoints=http"
      - "traefik.http.routers.owncloud.rule=Host(`cloud.owncloud.local`)"
      - "traefik.http.routers.owncloud.middlewares=https-redirect@file"
      - "traefik.http.routers.owncloud-secure.entrypoints=https"
      - "traefik.http.routers.owncloud-secure.rule=Host(`cloud.owncloud.local`)"
      - "traefik.http.routers.owncloud-secure.tls=true"
      - "traefik.http.routers.owncloud-secure.service=owncloud"
      - "traefik.http.services.owncloud.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis

networks:
  proxy:
    external: true

